name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '7.0'

jobs:
  code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Collect test code coverage
      run: |
        dotnet test \
          -p:CollectCoverage=true \
          -e:CoverletOutputFormat=opencover

    - name: Upload test code coverage report to codecov.io
      uses: codecov/codecov-action@v4

  build-and-test:
    name: Build and test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    permissions:
      checks: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: |
        dotnet test UnityVersionBump.Core.Tests/UnityVersionBump.Core.Tests.csproj --logger "trx;LogFileName=test-results.trx"

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: ${{matrix.os}} Tests
        path: UnityVersionBump.Core.Tests/TestResults/test-results.trx
        reporter: dotnet-trx
